window.esdocSearchIndex = [
  [
    "@aureooms/js-rational/src/constants/decimal_prefix.js~decimal_prefix",
    "variable/index.html#static-variable-DECIMAL_PREFIX",
    "<span>DECIMAL_PREFIX</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/constants/DECIMAL_PREFIX.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-rational/src/constants/fraction_sep.js~fraction_sep",
    "variable/index.html#static-variable-FRACTION_SEP",
    "<span>FRACTION_SEP</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/constants/FRACTION_SEP.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-rational/src/constants/repetend_prefix.js~repetend_prefix",
    "variable/index.html#static-variable-REPETEND_PREFIX",
    "<span>REPETEND_PREFIX</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/constants/REPETEND_PREFIX.js</span>",
    "variable"
  ],
  [
    "@aureooms/js-rational/src/_add.js~_add",
    "function/index.html#static-function-_add",
    "<span>_add</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_add.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_cmp.js~_cmp",
    "function/index.html#static-function-_cmp",
    "<span>_cmp</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_cmp.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_cmp_no_bounds.js~_cmp_no_bounds",
    "function/index.html#static-function-_cmp_no_bounds",
    "<span>_cmp_no_bounds</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_cmp_no_bounds.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_decimals.js~_decimals",
    "function/index.html#static-function-_decimals",
    "<span>_decimals</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_decimals.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_digits.js~_digits",
    "function/index.html#static-function-_digits",
    "<span>_digits</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_digits.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_div.js~_div",
    "function/index.html#static-function-_div",
    "<span>_div</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_div.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_mul.js~_mul",
    "function/index.html#static-function-_mul",
    "<span>_mul</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_mul.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_parse_fixed_point.js~_parse_fixed_point",
    "function/index.html#static-function-_parse_fixed_point",
    "<span>_parse_fixed_point</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_parse_fixed_point.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_parse_fraction.js~_parse_fraction",
    "function/index.html#static-function-_parse_fraction",
    "<span>_parse_fraction</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_parse_fraction.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_pow.js~_pow",
    "function/index.html#static-function-_pow",
    "<span>_pow</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_pow.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_simplify.js~_simplify",
    "function/index.html#static-function-_simplify",
    "<span>_simplify</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_simplify.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_stringify_digits.js~_stringify_digits",
    "function/index.html#static-function-_stringify_digits",
    "<span>_stringify_digits</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_stringify_digits.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_sub.js~_sub",
    "function/index.html#static-function-_sub",
    "<span>_sub</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_sub.js</span>",
    "function"
  ],
  [
    "@aureooms/js-rational/src/_transient.js~_transient",
    "function/index.html#static-function-_transient",
    "<span>_transient</span> <span class=\"search-result-import-path\">@aureooms/js-rational/src/_transient.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/_add.js",
    "file/src/_add.js.html",
    "src/_add.js",
    "file"
  ],
  [
    "src/_cmp.js",
    "file/src/_cmp.js.html",
    "src/_cmp.js",
    "file"
  ],
  [
    "src/_cmp_no_bounds.js",
    "file/src/_cmp_no_bounds.js.html",
    "src/_cmp_no_bounds.js",
    "file"
  ],
  [
    "src/_decimals.js",
    "file/src/_decimals.js.html",
    "src/_decimals.js",
    "file"
  ],
  [
    "src/_digits.js",
    "file/src/_digits.js.html",
    "src/_digits.js",
    "file"
  ],
  [
    "src/_div.js",
    "file/src/_div.js.html",
    "src/_div.js",
    "file"
  ],
  [
    "src/_mul.js",
    "file/src/_mul.js.html",
    "src/_mul.js",
    "file"
  ],
  [
    "src/_parse_fixed_point.js",
    "file/src/_parse_fixed_point.js.html",
    "src/_parse_fixed_point.js",
    "file"
  ],
  [
    "src/_parse_fraction.js",
    "file/src/_parse_fraction.js.html",
    "src/_parse_fraction.js",
    "file"
  ],
  [
    "src/_pow.js",
    "file/src/_pow.js.html",
    "src/_pow.js",
    "file"
  ],
  [
    "src/_simplify.js",
    "file/src/_simplify.js.html",
    "src/_simplify.js",
    "file"
  ],
  [
    "src/_stringify_digits.js",
    "file/src/_stringify_digits.js.html",
    "src/_stringify_digits.js",
    "file"
  ],
  [
    "src/_sub.js",
    "file/src/_sub.js.html",
    "src/_sub.js",
    "file"
  ],
  [
    "src/_transient.js",
    "file/src/_transient.js.html",
    "src/_transient.js",
    "file"
  ],
  [
    "src/constants/decimal_prefix.js",
    "file/src/constants/DECIMAL_PREFIX.js.html",
    "src/constants/DECIMAL_PREFIX.js",
    "file"
  ],
  [
    "src/constants/fraction_sep.js",
    "file/src/constants/FRACTION_SEP.js.html",
    "src/constants/FRACTION_SEP.js",
    "file"
  ],
  [
    "src/constants/repetend_prefix.js",
    "file/src/constants/REPETEND_PREFIX.js.html",
    "src/constants/REPETEND_PREFIX.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]